[tool.poetry]
name = "zulip-reader"
version = "0.1.0"
description = ""
authors = ["Daniel Kopecký <kopecky.d@gmail.com>"]
readme = "README.md"
packages = [{ include = "zulip_reader" }]

[tool.poetry.dependencies]
python = "^3.12"
zulip = "^0.9.0"
arrow = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
zulip-reader = "zulip_reader.cli:main"
